import type { Metadata } from "next";
import { Inter, Rajdhani } from "next/font/google";
import "./globals.css";
import { AuthMenu as ClientAuthMenu } from "@/components/AuthMenu";
import { AuthInit } from "@/components/AuthInit";
import { NavLinks } from "@/components/NavLinks";

const inter = Inter({ variable: "--font-inter", subsets: ["latin"], display: 'swap' });
const rajdhani = Rajdhani({ variable: "--font-rajdhani", weight: ["600","700"], subsets: ["latin"], display: 'swap' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} ${rajdhani.variable} antialiased bg-[var(--gh-bg)] text-[var(--gh-text)]`}>
        <AuthInit />
        <div className="mx-auto max-w-[1200px] px-6">
          <header className="sticky top-0 z-40 border-b border-[var(--gh-border)] bg-[color:var(--gh-bg)]/80 backdrop-blur supports-[backdrop-filter]:bg-[color:var(--gh-bg)]/60">
            <div className="h-14 flex items-center gap-4">
              <a href="/" className="font-display">GlyphHub</a>
              <NavLinks />
              <div className="ml-2 flex items-center gap-2">
                <span className="text-[var(--gh-text-muted)]">·</span>
                <ClientAuthMenu />
              </div>
            </div>
          </header>
          <main className="py-8">{children}</main>
          <footer className="border-t border-[var(--gh-border)] text-[var(--gh-text-muted)]">
            <div className="py-6 text-sm">© GlyphHub</div>
          </footer>
        </div>
      </body>
    </html>
  );
}
